#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: R
# autospec version: v26
# autospec commit: 99a7985
#
Name     : R-randomForestSRC
Version  : 3.4.0
Release  : 25
URL      : https://ftp.osuosl.org/pub/cran/src/contrib/randomForestSRC_3.4.0.tar.gz
Source0  : https://ftp.osuosl.org/pub/cran/src/contrib/randomForestSRC_3.4.0.tar.gz
Summary  : Fast Unified Random Forests for Survival, Regression, and
Group    : Development/Tools
License  : GPL-3.0
Requires: R-randomForestSRC-lib = %{version}-%{release}
Requires: R-DiagrammeR
Requires: R-data.tree
BuildRequires : R-DiagrammeR
BuildRequires : R-data.tree
BuildRequires : buildreq-R
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
No detailed description available

%package lib
Summary: lib components for the R-randomForestSRC package.
Group: Libraries

%description lib
lib components for the R-randomForestSRC package.


%prep
%setup -q -n randomForestSRC
pushd ..
cp -a randomForestSRC buildavx2
popd
pushd ..
cp -a randomForestSRC buildavx512
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1748356556

%install
export SOURCE_DATE_EPOCH=1748356556
rm -rf %{buildroot}
LANG=C.UTF-8
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -flto -fno-semantic-interposition "
FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -flto -fno-semantic-interposition "
AR=gcc-ar
RANLIB=gcc-ranlib
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library
mkdir -p %{buildroot}-v3/usr/lib64/R/library
mkdir -p %{buildroot}-v4/usr/lib64/R/library
mkdir -p %{buildroot}-va/usr/lib64/R/library

mkdir -p ~/.R
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL  --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}-v3/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --preclean  --install-tests --use-LTO --no-test-load --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}-v4/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean  --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :

/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}
/usr/bin/elf-move.py avx512 %{buildroot}-v4 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/usr/lib64/R/library/randomForestSRC/CITATION
/usr/lib64/R/library/randomForestSRC/DESCRIPTION
/usr/lib64/R/library/randomForestSRC/INDEX
/usr/lib64/R/library/randomForestSRC/Meta/Rd.rds
/usr/lib64/R/library/randomForestSRC/Meta/data.rds
/usr/lib64/R/library/randomForestSRC/Meta/features.rds
/usr/lib64/R/library/randomForestSRC/Meta/hsearch.rds
/usr/lib64/R/library/randomForestSRC/Meta/links.rds
/usr/lib64/R/library/randomForestSRC/Meta/nsInfo.rds
/usr/lib64/R/library/randomForestSRC/Meta/package.rds
/usr/lib64/R/library/randomForestSRC/NAMESPACE
/usr/lib64/R/library/randomForestSRC/NEWS
/usr/lib64/R/library/randomForestSRC/R/randomForestSRC
/usr/lib64/R/library/randomForestSRC/R/randomForestSRC.rdb
/usr/lib64/R/library/randomForestSRC/R/randomForestSRC.rdx
/usr/lib64/R/library/randomForestSRC/data/breast.rda
/usr/lib64/R/library/randomForestSRC/data/follic.rda
/usr/lib64/R/library/randomForestSRC/data/hd.rda
/usr/lib64/R/library/randomForestSRC/data/housing.rda
/usr/lib64/R/library/randomForestSRC/data/nutrigenomic.rda
/usr/lib64/R/library/randomForestSRC/data/pbc.rda
/usr/lib64/R/library/randomForestSRC/data/peakVO2.rda
/usr/lib64/R/library/randomForestSRC/data/vdv.rda
/usr/lib64/R/library/randomForestSRC/data/veteran.rda
/usr/lib64/R/library/randomForestSRC/data/wihs.rda
/usr/lib64/R/library/randomForestSRC/data/wine.rda
/usr/lib64/R/library/randomForestSRC/help/AnIndex
/usr/lib64/R/library/randomForestSRC/help/aliases.rds
/usr/lib64/R/library/randomForestSRC/help/paths.rds
/usr/lib64/R/library/randomForestSRC/help/randomForestSRC.rdb
/usr/lib64/R/library/randomForestSRC/help/randomForestSRC.rdx
/usr/lib64/R/library/randomForestSRC/html/00Index.html
/usr/lib64/R/library/randomForestSRC/html/R.css

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/R/library/randomForestSRC/libs/randomForestSRC.so
/V4/usr/lib64/R/library/randomForestSRC/libs/randomForestSRC.so
/usr/lib64/R/library/randomForestSRC/libs/randomForestSRC.so
